name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    repositories:
      - upstream/repository-name
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci
      
	- name: Test
      run: npm run test

    - name: Build
      run: npm run build
